#!/usr/bin/env python3

import argparse
from ehex.ehexsolver import solve


def main():

    parser = argparse.ArgumentParser(description='EHEX solver.')
    parser.add_argument('file', metavar='FILE', type=argparse.FileType('r'))
    parser.add_argument('-m', type=int)
    parser.add_argument('-d', action="store_true")

    args = parser.parse_args()
    solve(args.file.name, debug=args.d, max_level=args.m)


if __name__ == '__main__':
    main()
